language: node_js
node_js:
- lts/*
git:
  depth: 3
addons:
  apt:
    packages:
    - expect-dev
cache:
- pip
- npm
before_install: travis_scripts/before_install.sh
install:
- npm ci
stages:
- preparation
- name: build
  if: (branch = future OR branch = production-amp-dev) AND type != pull_request
- name: deploy
  if: (branch = future OR branch = production-amp-dev) AND type != pull_request
jobs:
  include:
  - stage: preparation
    name: Check code, import documents, build samples, playground & boilerplate
    before_script:
    - unbuffer gulp buildSamples
    - unbuffer gulp lintAll
    script: travis_scripts/preparation.sh
  - stage: build
    install: &1
    - npm ci
    - pip install grow==0.7.4 --user
    name: Build Pages (EN)
    script: unbuffer gulp buildPages --locales en
  - stage: build
    install: *1
    name: Build Pages (FR)
    script: unbuffer gulp buildPages --locales fr
  - stage: build
    install: *1
    name: Build Pages (AR)
    script: unbuffer gulp buildPages --locales ar
  - stage: build
    install: *1
    name: Build Pages (ES)
    script: unbuffer gulp buildPages --locales es
  - stage: build
    install: *1
    name: Build Pages (IT)
    script: unbuffer gulp buildPages --locales it
  - stage: build
    install: *1
    name: Build Pages (ID)
    script: unbuffer gulp buildPages --locales id
  - stage: build
    install: *1
    name: Build Pages (JA)
    script: unbuffer gulp buildPages --locales ja
  - stage: build
    install: *1
    name: Build Pages (KO)
    script: unbuffer gulp buildPages --locales ko
  - stage: build
    install: *1
    name: Build Pages (BR)
    script: unbuffer gulp buildPages --locales pt_BR
  - stage: build
    install: *1
    name: Build Pages (RU)
    script: unbuffer gulp buildPages --locales ru
  - stage: build
    install: *1
    name: Build Pages (TR)
    script: unbuffer gulp buildPages --locales tr
  - stage: build
    install: *1
    name: Build Pages (CN)
    script: unbuffer gulp buildPages --locales zh_CN
  - stage: deploy
    script: travis_scripts/deploy.sh
