language: node_js
node_js:
  - "lts/*"

git:
  depth: 3

cache:
  pip: true
  directories:
    - node_modules

install:
  - pip install grow==0.6.5 --user
  - grow --version
  - npm install

deploy:
  provider: gae
  keyfile: ".staging-secret.json"
  project: amp-dev-staging
before_install:
- openssl aes-256-cbc -K $encrypted_d4a09416a845_key -iv $encrypted_d4a09416a845_iv
  -in .staging-secret.json.enc -out .staging-secret.json -d
on: production
