language: node_js
node_js:
- "node"

install:
- curl https://install.growsdk.org | bash
- npm install -g gulp
- npm install

script:
- grow build

after_success:
- firebase deploy --token "$FIREBASE_TOKEN"

branches:
  only:
  - megamerge

env:
- secure: tXQTtZ/Q9A9Jyp8grH3IVWwArOQxNGCsj1s8OBMPdoMAK1FDbS4FNLQ9WN3KAqipzVPgz7vVcKxbEL0gj8MeEuuQLDliDR8gDzYBBSL2r51SPgcd5e1+kPrbl2X92HulDEK49SF8b69666oM2fp6EXUhIH/V/XjioiSops+TocQTKmi1cNi6VZPI4pCdHXMbTyddt2Dp6HrLC9RULW+2DzL2nhCJSeC0vWSzMp9GIu3lRmZKDRoSW6HRoWX5EnPvPGuLFUyf7qGC3D5sZKfDvojFwsYS97t/lsyUxJTphifUs/TyBgtRkEUhlp6pzR9eZ0r/qY/x9tyYjivsN00F3TUkm07hQrBJlMd9eteOfORneFIbaNDSbrBXTLbUVAt5yijWcjYoQ36i+5fxguaXLM5ZOR7Xfz/bS1QsEt0M5HZXBM4uMg7KfeZqcFZVijgSlmgYBZYfVui7R4BtBDfroYRKimllzLOhiakYickKoE+nBkcpvfiYqisoJ5+i6jBnMvS4ui/nHvcPp0MrN85HSLE2knrHb/Wegy5txUJ7Mu33AU+ypshmu0Lz6YE+zn3cIvm00sMFPjLvNT44mwMQQP3wj7/0BAaYUqAzqMytJlJcF31sK1dtT5H9BjZqQX9ssaHl0ALgWgGV0szNzcEJ3Xr59maIQIXNnFlC55fI57I=
- secure: kgGH1p2jOgPhSsw+xgIX/Qqncg8U1dpGnB5KwlRwHfvwfpIbsRHM52MFRcWr7TdWAkq9E9TKuBy5RlO3KLXKtW6/A56VDIsmD+tnBgW4w9GarxA8uA96rpH08jzhSS8en1g0jLuU0v7nB12XIrN60hXj/fEXAQgEaKCYjxNfpPu6kW3ANfCkECR2RcHFVPbkCLgAtAiclZaZC/dqgxZGJwHJyom3xYmuaA/PbkTbudXlosao+//EJVC4LgL1VA9TtonGzvnpH464Mcxj5/4xB+J+cr7nWdgZuHEO4/0+nNEzinoYqBUzOVpFVd4ozQDvViQ0BqJXm0e+47Tur2IPhHyu2Y7AmbFKqBb0O8NoPqw+xVeERg11ACTwmi4itopfTw0198l8/rm6/ICE1lk/mU0ePWoEfm2uP3SZXrwmWPMOlJj8qzMBvwpHM56czkSs5MxLZLZGPtgJcGz5GJGTg4OgEXET2QO668oaAUyUnTtzNeQ6C3s/eka6yXRsV88Qu1HOrN8dWiatCEfuNHZCPDXiB+ta9KRhlR0+QEIj/1W+vEI41oZSVigkFXBrVP0ZAj2F0ybISrBBw8HVcSilY1AZxbSb3AjLs2h8UUtlfdJ7eQy41EaW4RsYQc1OiJQjqJ0gcvmPd85IhTdWsHYZ8wXi/AqUjCU1HO/eLtK3eD8=
- secure: BlCm9CFLho9YSvH3FLhj4HD0p8rPWBRwMWVlBrljBvHf6Cvc0jBagNg9EuOGnS+DnkXe2UwuwevUJlzSSzWiPSksbKkyyPyh8FMCq0KzKztQbIuIqDTlsb7G0NbReuvmHScb58RGdMdgudK6VPG4+m/h+xl4/0IKvLvtQwYtAFN1U41Dyc/O4lFvELVCW1XzwDH1wd16MOmGGGb3H1XOda7EdIeFO6vyTstrjYScURpZHpS2oJ8xcOafdHYdbRe8V3bFz37II/u6Aj5o//Vi4p0CxvgDj8wmga7Aw1ZJO0KHNnYK/3ynp9DgxtXld6oXNPVFrRhwuSG8mXn+SDACnatmcW9Cig6VmlqHSquOMCEf0xHfCDBfiC9tVEepOy2MirfskNXdUiB+ErP0uGYQpHskRJI2U8k9HRKbseDHTNpC4g5jySo0/+y7Bois9kpE8LbQeIf+6Lzu9WUBM6ZtNVUW/mAlH13/MVueruBdTy1/2J9d/+P5ZiPu428n5xnXD5sKVJOi7UkhLj3fPoX9L9yyFjK4BnenocUf+Fy8RcHBTyriO1xkSXVi7L4c3jFGJ/OV+BXftDmzpQaUTfLmmbg4BWqzCmXNBpzZU/wFFyCdhjLlJtLfEt1qRsdoj3qcWn8c2IZ56yPczXBJv3g+HSVZLReFmN6skZ42Qc8BAys=
