# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AMP Project Documentation
description: > # this means to ignore newlines until "baseurl:"
  The official documentation for the AMP Project, including AMP JS,
  AMP HTML and more.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://ampproject.org" # the base hostname & protocol for your site

collections:
  get_started: 
    title: Get Started
    output: true
  guides:
    title: Guides
    output: true
  reference:
    title: Reference
    output: true
  support:
    title: Support
    output: true

# Build settings
markdown: kramdown

sass:
  style: compressed
